<a href="https://colab.research.google.com/github/kaykesm/MLCB_CK_2026/blob/main/C%C3%B3digoAtividade02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
# ==============================================================================
# ATIVIDADE 2 - CHATBOT VERSÃO 2
# DECISION TREE
# SAC MÓVEIS RESIDENCIAIS
# ==============================================================================

import numpy as np
import pandas as pd

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.tree import DecisionTreeClassifier
from sklearn.pipeline import Pipeline
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.model_selection import train_test_split


# ==============================================================================
# 1. CARREGAR O DATASET
# ==============================================================================

df = pd.read_csv('dataset_moveis_100.csv')

print("Dataset carregado com sucesso!")
print("Quantidade de registros:", len(df))

print("\nDistribuição das intenções:")
print(df['intencao'].value_counts())


# ==============================================================================
# 2. DIVISÃO DOS DADOS EM TREINO E TESTE
# ==============================================================================

X_train, X_test, y_train, y_test = train_test_split(
    df['texto'],
    df['intencao'],
    test_size=0.30,
    random_state=42,
    stratify=df['intencao']
)

print("\n==============================================")
print("DIVISÃO DOS DADOS")
print("==============================================")

print("Dados de treinamento:", len(X_train))
print("Dados de teste:", len(X_test))


# ==============================================================================
# 3. CRIAÇÃO DA PIPELINE
# ==============================================================================

pipeline_tree = Pipeline([
    ('vectorizer', TfidfVectorizer()),

    ('classifier', DecisionTreeClassifier(
        random_state=42
    ))
])

print("\nPipeline Decision Tree criada com sucesso!")


# ==============================================================================
# 4. TREINAMENTO DO MODELO
# ==============================================================================

pipeline_tree.fit(
    X_train,
    y_train
)

print("Modelo Decision Tree treinado com sucesso!")


# ==============================================================================
# 5. PREVISÕES NO CONJUNTO DE TESTE
# ==============================================================================

y_pred = pipeline_tree.predict(
    X_test
)


# ==============================================================================
# 6. MATRIZ DE CONFUSÃO
# ==============================================================================

print("\n==============================================")
print("MATRIZ DE CONFUSÃO - DECISION TREE")
print("==============================================")

matriz = confusion_matrix(
    y_test,
    y_pred
)

print(matriz)


# ==============================================================================
# 7. RELATÓRIO DE CLASSIFICAÇÃO
# ==============================================================================

print("\n==============================================")
print("CLASSIFICATION REPORT - DECISION TREE")
print("==============================================")

print(
    classification_report(
        y_test,
        y_pred
    )
)


# ==============================================================================
# 8. ACURÁCIA
# ==============================================================================

acuracia = np.mean(
    y_pred == y_test
)

print("Acurácia Geral:", f"{acuracia:.2%}")


# ==============================================================================
# 9. TESTES MANUAIS - 8 INPUTS
# ==============================================================================

LIMIAR_CONFIANCA = 0.50

print("\n==============================================")
print("BATERIA DE TESTES - DECISION TREE")
print("8 INPUTS OBRIGATÓRIOS")
print("==============================================")


for i in range(1, 9):

    print(f"\n[Teste {i}/8]")

    # Entrada do usuário
    frase = input(
        "Digite a frase do cliente: "
    ).strip()


    # Verificar se foi digitada uma frase
    if frase == "":

        print(
            "Desculpe, não entendi sua solicitação. "
            "Encaminhando você para um atendente humano..."
        )

        continue


    # Previsão da intenção
    intencao = pipeline_tree.predict(
        [frase]
    )[0]


    # Probabilidades
    probs = pipeline_tree.predict_proba(
        [frase]
    )[0]


    # Maior probabilidade
    maior_prob = np.max(
        probs
    )


    # ==============================================================================
    # 10. REGRA DE DECISÃO / FALLBACK
    # ==============================================================================

    if maior_prob >= LIMIAR_CONFIANCA:

        print(
            f"Intenção identificada: {intencao}"
        )

        print(
            f"Confiança: {maior_prob:.2%}"
        )

    else:

        print(
            "Desculpe, não entendi sua solicitação. "
            "Encaminhando você para um atendente humano..."
        )

        print(
            f"Maior confiança encontrada: {maior_prob:.2%}"
        )


# ==============================================================================
# FIM
# ==============================================================================

print("\n==============================================")
print("ATIVIDADE 2 FINALIZADA")
print("==============================================")


Dataset carregado com sucesso!
Quantidade de registros: 100

Distribuição das intenções:
intencao
vendas                20
suporte               20
trocas_devolucoes     20
reclamacoes           20
logistica_entregas    20
Name: count, dtype: int64

DIVISÃO DOS DADOS
Dados de treinamento: 70
Dados de teste: 30

Pipeline Decision Tree criada com sucesso!
Modelo Decision Tree treinado com sucesso!

MATRIZ DE CONFUSÃO - DECISION TREE
[[4 0 0 0 2]
 [1 4 1 0 0]
 [0 0 6 0 0]
 [0 0 1 5 0]
 [0 0 0 1 5]]

CLASSIFICATION REPORT - DECISION TREE
                    precision    recall  f1-score   support

logistica_entregas       0.80      0.67      0.73         6
       reclamacoes       1.00      0.67      0.80         6
           suporte       0.75      1.00      0.86         6
 trocas_devolucoes       0.83      0.83      0.83         6
            vendas       0.71      0.83      0.77         6

          accuracy                           0.80        30
         macro avg       0.82      0.8